### ISSUE TITLE
Audio sources

### ISSUE THREAD

**Issue by gseidel** [indivisualvj/indivisual#7]
At the moment we can use the microphone (I also read about midi) as audio source to generate visualisation.

Wouldn't it be nice if we could use this as well?

* Upload a audio file
* Use Soundcloud API
* Use Spotify API

I don't know if you could use the API for this features, but i created this ticket also to evaluate audio sources for future and keep track on it.

**Comment by indivisualvj** [comment]
I like this.
I already had this working with local files and i know it is possible to connect WebAdio AnalyserNodes to HTML audio tags.
I know that shadertoy.com have the ability to include audio from soundcloud to then use it in their shadertool. But i have no idea how they did that. 
There also should be an extra panel to manage audio settings instead of having it all in one controller.

**Comment by indivisualvj** [comment]
File upload and Soundcloud API are included now.

**Comment by indivisualvj** [comment]
file upload + soundcloud audio sources fixed in #11
